### ISSUE TITLE
Is the coordinate system messed up, or am I stupid?

### ISSUE THREAD

**Issue by frarf** [noonat/intersect#3]
I'm currently following this tutorial in hopes of accurately recreating it in Lua. However, immediately starting from the AABB vs Point section, I had issues with the coordinate system.  
The point would be detected when it shouldn't, wouldn't be when it should, hit values aren't accurate, etc.    

So I ask, what exactly is the coordinate system used here? Is it based on the center? The top-left?  
I'm guessing the latter since this is likely used with canvas, but I have issues there, too.    

I think the easiest way for me to debug this is to ask: how did you create the visualization in the AABB vs Point section? If I can know that, I'd be able to debug it, I think.   
Thanks for the great tutorial!

**Comment by frarf** [comment]
Apologies, I missed the part where you said that AABBs are defined by their center points.

**Comment by noonat** [comment]
@frarf Glad you figured it out!
